reference: /pellmanlab/logan/references/GRCm38.p6.genome.fa
intervals: /pellmanlab/logan/references/GRCm38.bed
gatk_cmd: 'gatk --java-options "-Xmx14G"'
max_records: 2000000
tmp_dir: 'tmp'
fastq_dir: '/czlab/lblaine/data/mouse_embryo'
