reference: /pellmanlab/logan/references/GRCm38.p6.genome.fa
samples: samples.tsv
gatk_cmd: 'gatk --java-options "-Xmx14G"'
max_records: 2000000
tmp_dir: '/czlab/lblaine/tmp'
fastq_dir: '/czlab/lblaine/data/mouse_embryo'
