reference: "references/GRCm38.p6.genome.fa"

samples:
  190809_1A: 1_HKVVVDSXX.1.ATTACTCG_TATAGCCT
  190809_1B: 1_HKVVVDSXX.1.ATTACTCG_ATAGAGGC
  190809_1C: 1_HKVVVDSXX.1.ATTACTCG_CCTATCCT
  190809_1D: 1_HKVVVDSXX.1.ATTACTCG_GGCTCTGA
  190809_1E: 1_HKVVVDSXX.1.ATTACTCG_AGGCGAAG
  190809_1F: 1_HKVVVDSXX.1.ATTACTCG_TAATCTTA
  190809_1G: 1_HKVVVDSXX.1.ATTACTCG_CAGGACGT
  190809_1H: 1_HKVVVDSXX.1.ATTACTCG_GTACTGAC
  190809_2A: 1_HKVVVDSXX.1.TCCGGAGA_TATAGCCT
  190809_2B: 1_HKVVVDSXX.1.TCCGGAGA_ATAGAGGC
  190809_2C: 1_HKVVVDSXX.1.TCCGGAGA_CCTATCCT
  190809_2D: 1_HKVVVDSXX.1.TCCGGAGA_GGCTCTGA
  190809_2E: 1_HKVVVDSXX.1.TCCGGAGA_AGGCGAAG
  190809_2F: 1_HKVVVDSXX.1.TCCGGAGA_TAATCTTA
  190809_2G: 1_HKVVVDSXX.1.TCCGGAGA_CAGGACGT
  190809_2H: 1_HKVVVDSXX.1.TCCGGAGA_GTACTGAC
  190809_4A: 1_HKVVVDSXX.1.GAGATTCC_TATAGCCT
  190809_4B: 1_HKVVVDSXX.1.GAGATTCC_ATAGAGGC
  190809_4C: 1_HKVVVDSXX.1.GAGATTCC_CCTATCCT
  190809_4D: 1_HKVVVDSXX.1.GAGATTCC_GGCTCTGA
  190809_4E: 1_HKVVVDSXX.1.GAGATTCC_AGGCGAAG
  190809_4F: 1_HKVVVDSXX.1.GAGATTCC_TAATCTTA
  190809_4G: 1_HKVVVDSXX.1.GAGATTCC_CAGGACGT
  190809_4H: 1_HKVVVDSXX.1.GAGATTCC_GTACTGAC
  190809_10A: 2_HKVVVDSXX.2.TCCGCGAA_TATAGCCT
  190809_10C: 2_HKVVVDSXX.2.TCCGCGAA_CCTATCCT
  190809_5A: 2_HKVVVDSXX.2.ATTCAGAA_TATAGCCT
  190809_5B: 2_HKVVVDSXX.2.ATTCAGAA_ATAGAGGC
  190809_5C: 2_HKVVVDSXX.2.ATTCAGAA_CCTATCCT
  190809_5D: 2_HKVVVDSXX.2.ATTCAGAA_GGCTCTGA
  190809_5E: 2_HKVVVDSXX.2.ATTCAGAA_AGGCGAAG
  190809_5F: 2_HKVVVDSXX.2.ATTCAGAA_TAATCTTA
  190809_5G: 2_HKVVVDSXX.2.ATTCAGAA_CAGGACGT
  190809_5H: 2_HKVVVDSXX.2.ATTCAGAA_GTACTGAC
  190809_7A: 2_HKVVVDSXX.2.CTGAAGCT_TATAGCCT
  190809_7B: 2_HKVVVDSXX.2.CTGAAGCT_ATAGAGGC
  190809_7C: 2_HKVVVDSXX.2.CTGAAGCT_CCTATCCT
  190809_7D: 2_HKVVVDSXX.2.CTGAAGCT_GGCTCTGA
  190809_7E: 2_HKVVVDSXX.2.CTGAAGCT_AGGCGAAG
  190809_7F: 2_HKVVVDSXX.2.CTGAAGCT_TAATCTTA
  190809_8A: 2_HKVVVDSXX.2.TAATGCGC_TATAGCCT
  190809_8B: 2_HKVVVDSXX.2.TAATGCGC_ATAGAGGC
  190809_8C: 2_HKVVVDSXX.2.TAATGCGC_CCTATCCT
  190809_8D: 2_HKVVVDSXX.2.TAATGCGC_GGCTCTGA
  190809_8E: 2_HKVVVDSXX.2.TAATGCGC_AGGCGAAG
  190809_8F: 2_HKVVVDSXX.2.TAATGCGC_TAATCTTA
  190809_8G: 2_HKVVVDSXX.2.TAATGCGC_CAGGACGT
  190809_8H: 2_HKVVVDSXX.2.TAATGCGC_GTACTGAC
  190808_6A: 3_HKVVVDSXX.3.GAATTCGT_TATAGCCT
  190808_6B: 3_HKVVVDSXX.3.GAATTCGT_ATAGAGGC
  190808_6C: 3_HKVVVDSXX.3.GAATTCGT_CCTATCCT
  190808_6D: 3_HKVVVDSXX.3.GAATTCGT_GGCTCTGA
  190808_6E: 3_HKVVVDSXX.3.GAATTCGT_AGGCGAAG
  190808_6F: 3_HKVVVDSXX.3.GAATTCGT_TAATCTTA
  190808_6G: 3_HKVVVDSXX.3.GAATTCGT_CAGGACGT
  190808_6H: 3_HKVVVDSXX.3.GAATTCGT_GTACTGAC
  190808_7A: 3_HKVVVDSXX.3.CTGAAGCT_TATAGCCT
  190808_7B: 3_HKVVVDSXX.3.CTGAAGCT_ATAGAGGC
  190808_7C: 3_HKVVVDSXX.3.CTGAAGCT_CCTATCCT
  190808_7D: 3_HKVVVDSXX.3.CTGAAGCT_GGCTCTGA
  190808_7E: 3_HKVVVDSXX.3.CTGAAGCT_AGGCGAAG
  190808_7F: 3_HKVVVDSXX.3.CTGAAGCT_TAATCTTA
  190808_7G: 3_HKVVVDSXX.3.CTGAAGCT_CAGGACGT
  190808_7H: 3_HKVVVDSXX.3.CTGAAGCT_GTACTGAC
  190808_8A: 3_HKVVVDSXX.3.TAATGCGC_TATAGCCT
  190808_8B: 3_HKVVVDSXX.3.TAATGCGC_ATAGAGGC
  190808_8C: 3_HKVVVDSXX.3.TAATGCGC_CCTATCCT
  190808_8D: 3_HKVVVDSXX.3.TAATGCGC_GGCTCTGA
  190809_10B: 3_HKVVVDSXX.3.TCCGCGAA_ATAGAGGC
  190809_10D: 3_HKVVVDSXX.3.TCCGCGAA_GGCTCTGA
  190809_10E: 3_HKVVVDSXX.3.TCCGCGAA_AGGCGAAG
  190809_10F: 3_HKVVVDSXX.3.TCCGCGAA_TAATCTTA
  190809_10G: 3_HKVVVDSXX.3.TCCGCGAA_CAGGACGT
  190809_10H: 3_HKVVVDSXX.3.TCCGCGAA_GTACTGAC
  190808_10A: 4_HKVVVDSXX.4.TCCGCGAA_TATAGCCT
  190808_10B: 4_HKVVVDSXX.4.TCCGCGAA_ATAGAGGC
  190808_10C: 4_HKVVVDSXX.4.TCCGCGAA_CCTATCCT
  190808_10D: 4_HKVVVDSXX.4.TCCGCGAA_GGCTCTGA
  190808_10E: 4_HKVVVDSXX.4.TCCGCGAA_AGGCGAAG
  190808_10F: 4_HKVVVDSXX.4.TCCGCGAA_TAATCTTA
  190808_10G: 4_HKVVVDSXX.4.TCCGCGAA_CAGGACGT
  190808_11A: 4_HKVVVDSXX.4.TCTCGCGC_TATAGCCT
  190808_11B: 4_HKVVVDSXX.4.TCTCGCGC_ATAGAGGC
  190808_11C: 4_HKVVVDSXX.4.TCTCGCGC_CCTATCCT
  190808_11D: 4_HKVVVDSXX.4.TCTCGCGC_GGCTCTGA
  190808_11E: 4_HKVVVDSXX.4.TCTCGCGC_AGGCGAAG
  190808_11F: 4_HKVVVDSXX.4.TCTCGCGC_TAATCTTA
  190808_8E: 4_HKVVVDSXX.4.TAATGCGC_AGGCGAAG
  190808_8F: 4_HKVVVDSXX.4.TAATGCGC_TAATCTTA
  190808_8G: 4_HKVVVDSXX.4.TAATGCGC_CAGGACGT
  190808_8H: 4_HKVVVDSXX.4.TAATGCGC_GTACTGAC
  190808_9A: 4_HKVVVDSXX.4.CGGCTATG_TATAGCCT
  190808_9B: 4_HKVVVDSXX.4.CGGCTATG_ATAGAGGC
  190808_9C: 4_HKVVVDSXX.4.CGGCTATG_CCTATCCT
  190808_9D: 4_HKVVVDSXX.4.CGGCTATG_GGCTCTGA
  190808_9E: 4_HKVVVDSXX.4.CGGCTATG_AGGCGAAG
  190808_9F: 4_HKVVVDSXX.4.CGGCTATG_TAATCTTA
  190808_9G: 4_HKVVVDSXX.4.CGGCTATG_CAGGACGT
  190808_9H: 4_HKVVVDSXX.4.CGGCTATG_GTACTGAC

