reference: /pellmanlab/logan/references/GRCm38.p6.genome.fa
intervals: /pellmanlab/logan/references/GRCm38.10kb_bins.bed
gatk_cmd: 'gatk --java-options "-Xmx14G -XX:ConcGCThreads=3"'
max_records: 2000000
tmp_dir: 'tmp'
samples: samples.tsv
snp_sites: '/pellmanlab/logan/data/mouse_bulk_seq/C57BL_129S1.mgp.v5.list'
simple_repeats: '/pellmanlab/logan/data/references/mm10/simpleRepeat.UCSC.mm10.bed'
germline_svs: '/pellmanlab/logan/data/mouse_bulk_seq/C57BL_129S1.SV.bed'
normals:
    - '/pellmanlab/logan/data/mouse_bulk_seq/C57BL_6NJ.reordered.bam'
    - '/pellmanlab/logan/data/mouse_bulk_seq/129S1_SvImJ.reordered.bam'
